#!/usr/bin/env bash
# setup.sh
# One-time first-run setup for the Content Image Suite.
#
# Detects which agent runtime the user has installed (Claude Code, Hermes
# Agent, or both), asks one question if ambiguous, persists the choice to
# ~/.content-image-suite/config, and dispatches to the appropriate
# installer. After the first run the choice is cached, so re-running
# setup.sh is a no-op unless --reconfigure is passed.
#
# Usage:
#   ./setup.sh                 # auto-detect, prompt if ambiguous, install
#   ./setup.sh --reconfigure   # ignore the cached choice and ask again
#   ./setup.sh --dry-run       # show what would happen, change nothing
#   ./setup.sh --force claude  # skip detection, install for Claude Code
#   ./setup.sh --force hermes  # skip detection, print Hermes tap command
#   ./setup.sh --force both    # do both
#
# This script delegates the actual installation to install.sh (or
# install-team.sh if the user picks the team variant). For Hermes it prints
# the `hermes skills tap add` command rather than running it, because
# Hermes may not be in $PATH at setup time.

set -euo pipefail

RED=$'\033[0;31m'
GREEN=$'\033[0;32m'
YELLOW=$'\033[1;33m'
BLUE=$'\033[0;34m'
BOLD=$'\033[1m'
NC=$'\033[0m'

CONFIG_DIR="$HOME/.content-image-suite"
CONFIG_FILE="$CONFIG_DIR/config"

DRY_RUN=0
RECONFIGURE=0
FORCE_RUNTIME=""

while [ $# -gt 0 ]; do
    case "$1" in
        --dry-run)      DRY_RUN=1; shift ;;
        --reconfigure)  RECONFIGURE=1; shift ;;
        --force)        FORCE_RUNTIME="${2:-}"; shift 2 ;;
        -h|--help)
            head -n 22 "$0" | tail -n 21 | sed 's/^# //; s/^#//'
            exit 0
            ;;
        *)
            echo "Unknown argument: $1" >&2
            echo "Try --help" >&2
            exit 2
            ;;
    esac
done

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

say()  { echo "${BLUE}${1}${NC}"; }
ok()   { echo "  ${GREEN}OK${NC} $1"; }
miss() { echo "  ${YELLOW}--${NC} $1"; }
warn() { echo "${YELLOW}${1}${NC}"; }
err()  { echo "${RED}${1}${NC}" >&2; }

read_config_value() {
    local key="$1"
    [ -f "$CONFIG_FILE" ] || return 1
    # Tolerate both "key = value" and "key=value". Uses sed for portability
    # (BSD awk on macOS lacks the gawk-only match() with capture arrays).
    sed -n -E "s/^[[:space:]]*${key}[[:space:]]*=[[:space:]]*(.*)$/\1/p" "$CONFIG_FILE" \
        | head -n 1
}

write_config() {
    mkdir -p "$CONFIG_DIR"
    {
        echo "# Content Image Suite — runtime configuration"
        echo "# Generated by setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
        echo "runtime = $1"
        echo "install_mode = $2"
        echo "setup_completed_at = $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    } > "$CONFIG_FILE"
}

# ---------------------------------------------------------------------------
# Runtime detection
# ---------------------------------------------------------------------------

# Returns "yes" or "no". Hermes is detected via env var, install dir, or PATH.
detect_hermes() {
    if [ -n "${HERMES_SKILL_DIR:-}" ]; then echo yes; return; fi
    if [ -d "$HOME/.hermes" ]; then echo yes; return; fi
    if [ -d "/opt/hermes" ]; then echo yes; return; fi
    if command -v hermes >/dev/null 2>&1; then echo yes; return; fi
    echo no
}

# Claude Code detection. Env var, install dir, or claude binary.
detect_claude() {
    if [ -n "${CLAUDE_PROJECT_DIR:-}" ]; then echo yes; return; fi
    if [ -d "$HOME/.claude" ]; then echo yes; return; fi
    if command -v claude >/dev/null 2>&1; then echo yes; return; fi
    echo no
}

# ---------------------------------------------------------------------------
# Cached-choice path
# ---------------------------------------------------------------------------

if [ -f "$CONFIG_FILE" ] && [ $RECONFIGURE -eq 0 ] && [ -z "$FORCE_RUNTIME" ]; then
    cached_runtime=$(read_config_value runtime || echo "")
    cached_mode=$(read_config_value install_mode || echo "")
    if [ -n "$cached_runtime" ]; then
        say "Cached configuration found: runtime=$cached_runtime, install_mode=$cached_mode"
        echo "  Config file: $CONFIG_FILE"
        echo ""
        echo "  Re-run with --reconfigure to choose a different runtime."
        echo "  Re-run with --force <runtime> to bypass detection for one install."
        exit 0
    fi
fi

# ---------------------------------------------------------------------------
# Decide which runtime to target
# ---------------------------------------------------------------------------

CHOSEN_RUNTIME=""

if [ -n "$FORCE_RUNTIME" ]; then
    case "$FORCE_RUNTIME" in
        claude|hermes|both) CHOSEN_RUNTIME="$FORCE_RUNTIME" ;;
        *) err "Unknown --force value: $FORCE_RUNTIME (expected claude, hermes, or both)"; exit 2 ;;
    esac
    say "Runtime forced via --force: $CHOSEN_RUNTIME"
else
    say "Detecting agent runtime..."
    HERMES_PRESENT=$(detect_hermes)
    CLAUDE_PRESENT=$(detect_claude)
    [ "$HERMES_PRESENT" = "yes" ] && ok "Hermes Agent detected" || miss "Hermes Agent not detected"
    [ "$CLAUDE_PRESENT" = "yes" ] && ok "Claude Code detected"  || miss "Claude Code not detected"
    echo ""

    if [ "$HERMES_PRESENT" = "yes" ] && [ "$CLAUDE_PRESENT" = "yes" ]; then
        echo "Both runtimes are available. Which is the primary target?"
        echo "  [1] Claude Code (install to ~/.claude/skills/)"
        echo "  [2] Hermes Agent (add this repo as a tap)"
        echo "  [3] Both runtimes"
        printf "Pick [1/2/3]: "
        read -r choice
        case "$choice" in
            1) CHOSEN_RUNTIME="claude" ;;
            2) CHOSEN_RUNTIME="hermes" ;;
            3) CHOSEN_RUNTIME="both" ;;
            *) err "Invalid choice. Aborting."; exit 2 ;;
        esac
    elif [ "$HERMES_PRESENT" = "yes" ]; then
        CHOSEN_RUNTIME="hermes"
        ok "Single runtime detected: targeting Hermes Agent"
    elif [ "$CLAUDE_PRESENT" = "yes" ]; then
        CHOSEN_RUNTIME="claude"
        ok "Single runtime detected: targeting Claude Code"
    else
        warn "No agent runtime detected on this machine."
        echo "Install one of the following first, then re-run setup.sh:"
        echo "  Claude Code: https://claude.com/claude-code"
        echo "  Hermes Agent: https://hermes-agent.nousresearch.com/"
        echo ""
        echo "Or pick a runtime to install for anyway:"
        echo "  [1] Claude Code"
        echo "  [2] Hermes Agent"
        echo "  [3] Cancel"
        printf "Pick [1/2/3]: "
        read -r choice
        case "$choice" in
            1) CHOSEN_RUNTIME="claude" ;;
            2) CHOSEN_RUNTIME="hermes" ;;
            *) err "Cancelled."; exit 0 ;;
        esac
    fi
fi

# ---------------------------------------------------------------------------
# For Claude Code, also decide solo vs team install
# ---------------------------------------------------------------------------

INSTALL_MODE="n/a"

if [ "$CHOSEN_RUNTIME" = "claude" ] || [ "$CHOSEN_RUNTIME" = "both" ]; then
    if [ -z "$FORCE_RUNTIME" ]; then
        echo ""
        echo "Claude Code install mode:"
        echo "  [1] Solo (copy every skill into ~/.claude/skills/, every platform active)"
        echo "  [2] Team (stage everything, activate only what you ask for, /suite to toggle)"
        printf "Pick [1/2]: "
        read -r mode_choice
        case "$mode_choice" in
            1) INSTALL_MODE="solo" ;;
            2) INSTALL_MODE="team" ;;
            *) err "Invalid choice. Aborting."; exit 2 ;;
        esac
    else
        INSTALL_MODE="solo"
    fi
fi

# ---------------------------------------------------------------------------
# Confirm and dispatch
# ---------------------------------------------------------------------------

echo ""
say "Plan"
echo "  Runtime:      $CHOSEN_RUNTIME"
echo "  Install mode: $INSTALL_MODE"
echo "  Config file:  $CONFIG_FILE"
if [ $DRY_RUN -eq 1 ]; then
    warn "DRY RUN. Nothing will be modified."
    exit 0
fi

case "$CHOSEN_RUNTIME" in
    claude)
        if [ "$INSTALL_MODE" = "team" ]; then
            bash "$SCRIPT_DIR/install-team.sh"
        else
            bash "$SCRIPT_DIR/install.sh"
        fi
        ;;
    hermes)
        echo ""
        say "Hermes Agent install (run this command yourself):"
        echo ""
        echo "  ${BOLD}hermes skills tap add varuntyagi83/content-image-suite${NC}"
        echo ""
        echo "  Then install whichever platform skills you want, for example:"
        echo "    hermes skills install varuntyagi83/visual-engine"
        echo "    hermes skills install varuntyagi83/linkedin-image-generator"
        echo ""
        echo "  Hermes lazy-loads skill bodies on demand, so the equivalent of"
        echo "  Claude's /suite toggle is unnecessary: you pay only the"
        echo "  metadata cost for skills you do not invoke."
        ;;
    both)
        if [ "$INSTALL_MODE" = "team" ]; then
            bash "$SCRIPT_DIR/install-team.sh"
        else
            bash "$SCRIPT_DIR/install.sh"
        fi
        echo ""
        say "Hermes Agent install (run this command yourself):"
        echo ""
        echo "  ${BOLD}hermes skills tap add varuntyagi83/content-image-suite${NC}"
        echo ""
        ;;
esac

write_config "$CHOSEN_RUNTIME" "$INSTALL_MODE"

echo ""
ok "Setup complete. Choice cached: $CONFIG_FILE"
echo ""
echo "Re-run setup.sh anytime: cached choice is honoured by default."
echo "Re-run with --reconfigure to change runtime or install mode."
